"""Op related tables

Revision ID: 419e2c1be18c
Revises: b80bde1a7b1f
Create Date: 2025-08-16 06:52:37.812205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419e2c1be18c'
down_revision = 'b80bde1a7b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('op_type', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_customer_email', ['email'])
        batch_op.create_unique_constraint('uq_customer_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customer_name', type_='unique')
        batch_op.drop_constraint('uq_customer_email', type_='unique')

    op.drop_table('operation_item')
    op.drop_table('operation')
    # ### end Alembic commands ###
