"""New model for book series

Revision ID: 97628f3aeb18
Revises: dc921115e122
Create Date: 2025-08-14 11:59:31.013081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97628f3aeb18'
down_revision = 'dc921115e122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_book_series_name')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serie_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_book_series_id', 'book_series', ['serie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_series_id', type_='foreignkey')
        batch_op.drop_column('serie_id')

    op.drop_table('book_series')
    # ### end Alembic commands ###
