"""Customer specific columns

Revision ID: b80bde1a7b1f
Revises: b988df01fcea
Create Date: 2025-08-14 17:59:41.616730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80bde1a7b1f'
down_revision = 'b988df01fcea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_series', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_book_series_name', ['name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_name', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('store_name')

    with op.batch_alter_table('book_series', schema=None) as batch_op:
        batch_op.drop_constraint('uq_book_series_name', type_='unique')

    # ### end Alembic commands ###
