"""Customer now User

Revision ID: b988df01fcea
Revises: 0f6269bf02ab
Create Date: 2025-08-14 17:40:48.604375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b988df01fcea'
down_revision = '0f6269bf02ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='uq_customer_email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_customer_name')
    )
    op.drop_table('customer')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_book_series_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_book_series_id', 'book_series', ['series_id'], ['id'])
        batch_op.drop_column('serie_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serie_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_book_series_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_book_series_id'), 'book_series', ['serie_id'], ['id'])
        batch_op.drop_column('series_id')

    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
